version: '3.8'
services:

  db:
    image: "postgres"
    ports:
      - "5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./deploy/prod/.env

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./deploy/prod/.env
    command: gunicorn --workers 3 core_config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

  nginx:
    build:
      context: ./deploy/nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: