# Generated by Django 3.2.5 on 2021-07-09 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL), ]

    operations = [migrations.CreateModel(name='Post', fields=[('id',
                                                               models.BigAutoField(
                                                                   auto_created=True,
                                                                   primary_key=True,
                                                                   serialize=False,
                                                                   verbose_name='ID')),
        ('title', models.CharField(default='Enter title...', max_length=255)),
        ('content', models.TextField(max_length=140)),
        ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
        ('is_published_to_telegram', models.BooleanField(default=False)), (
        'author',
        models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                          related_name='user_posts',
                          to=settings.AUTH_USER_MODEL)), ],
        options={'ordering': ['-created_at'], }, ), ]
